server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://100.106.249.45:3306/FinalGraduateDB?zeroDateTimeBehavior=convertToNull
    #    url: jdbc:mysql://localhost:3306/FinalGraduateDB?zeroDateTimeBehavior=convertToNull
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ltphat240103@gmail.com
    password: hjiv mfbn ddsw ksbt
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:9090/
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
jwt:
  secret: 9q7897937129387891375981312312312312131231192347192374973948712980347913274
  expiration: 86400000