name: Build Module

on:
  workflow_call:
    secrets:
      GITOPS_PAT:
        required: true
    inputs:
      module:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: 'build.dockerfile'
      context:
        required: false
        type: string
        default: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ inputs.module }}:${{ github.sha }}

          docker build \
            --build-arg MODULE=${{ inputs.module }} \
            -f ${{ inputs.dockerfile }} \
            -t $IMAGE \
            ${{ inputs.context }}

      - name: Push Docker
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ inputs.module }}:${{ github.sha }}
          docker push $IMAGE