name: Main Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  detect:
    uses: ./.github/workflows/detect-changes.yml

  build:
    needs: detect
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect.outputs.modules) }}

    uses: ./.github/workflows/build-module.yml
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
    with:
      module: ${{ matrix.module }}